# This file was generated by GoReleaser. DO NOT EDIT.
cask "choir" do
  name "choir"
  desc "Create isolated environments for AI agents to execute autonomously"
  homepage "https://github.com/Quidge/choir"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "choir"

  on_macos do
    on_intel do
      url "https://github.com/Quidge/choir/releases/download/v#{version}/choir_#{version}_darwin_amd64.tar.gz"
      sha256 "e107d35d445c72b8b0c7b20dae4330614259fda7b343c70b3cedee6a7e473764"
    end
    on_arm do
      url "https://github.com/Quidge/choir/releases/download/v#{version}/choir_#{version}_darwin_arm64.tar.gz"
      sha256 "de184acb1016b06ebb83819d9e8ee908295a094e836cd2f8d0e163933b88a162"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Quidge/choir/releases/download/v#{version}/choir_#{version}_linux_amd64.tar.gz"
      sha256 "879a709a102fe7bc82ef9d09ed46fb8de213455c018ae91c904b6a8a8f04ff70"
    end
    on_arm do
      url "https://github.com/Quidge/choir/releases/download/v#{version}/choir_#{version}_linux_arm64.tar.gz"
      sha256 "1e261da0b3081dd8a99d8086aafe87a4cd78fdec1d5c5d23b1dd9444507212e6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/choir"]
    end
  end

  # No zap stanza required
end
