# This file was generated by GoReleaser. DO NOT EDIT.
cask "choir" do
  name "choir"
  desc "Create isolated environments for AI agents to execute autonomously"
  homepage "https://github.com/Quidge/choir"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "choir"

  on_macos do
    on_intel do
      url "https://github.com/Quidge/choir/releases/download/v#{version}/choir_#{version}_darwin_amd64.tar.gz"
      sha256 "19456b0e93d1828f8092d6d559ce51b36bb3a163ac1752ecb6714cd972a7b3cd"
    end
    on_arm do
      url "https://github.com/Quidge/choir/releases/download/v#{version}/choir_#{version}_darwin_arm64.tar.gz"
      sha256 "d017bda17212cd37a09bfc2dced8d853967011d51ef05a9fa7ce995eca0bbfb8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Quidge/choir/releases/download/v#{version}/choir_#{version}_linux_amd64.tar.gz"
      sha256 "2246380128bb97826f3d81a984d772d2c4714266508a8208e842caddd1631417"
    end
    on_arm do
      url "https://github.com/Quidge/choir/releases/download/v#{version}/choir_#{version}_linux_arm64.tar.gz"
      sha256 "e042d78b1291d3ad7ff612a046fa0c863294993c0a6594edd6be8027c4514c5b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/choir"]
    end
  end

  # No zap stanza required
end
