# This file was generated by GoReleaser. DO NOT EDIT.
cask "choir" do
  name "choir"
  desc "Create isolated environments for AI agents to execute autonomously"
  homepage "https://github.com/Quidge/choir"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "choir"

  on_macos do
    on_intel do
      url "https://github.com/Quidge/choir/releases/download/v#{version}/choir_#{version}_darwin_amd64.tar.gz"
      sha256 "e059fcb58d1e36d1c5f6ac744baef11068e07f4f957fcf1637093a5ed041863e"
    end
    on_arm do
      url "https://github.com/Quidge/choir/releases/download/v#{version}/choir_#{version}_darwin_arm64.tar.gz"
      sha256 "a94556bc29c7999fda644e8bc3513a1199e437723c4c4d417902a022a50fc5be"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Quidge/choir/releases/download/v#{version}/choir_#{version}_linux_amd64.tar.gz"
      sha256 "709b5d2b9eaf35b9a682aca237dd6bde212c40063eea15061d66ba0a69873861"
    end
    on_arm do
      url "https://github.com/Quidge/choir/releases/download/v#{version}/choir_#{version}_linux_arm64.tar.gz"
      sha256 "0a1123755d1208e533a1a76cc67a75be66faaba7c0f2300848584ef447fc74e7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/choir"]
    end
  end

  # No zap stanza required
end
